"""Regenerate the autogenerated region of changelog.mdx from published releases.

The changelog has two parts:

- Everything above the `AUTOGEN:START` marker is hand-maintained (the intro).
- The region between the markers is produced here from GitHub release data,
  so version tables can never drift from what was actually published.

Editorial prose lives in `automation/changelog-notes.md`, keyed by month. The
generator splices each month's note into that month's entry. This keeps the
mechanical data automatic and the prose human, without either clobbering the
other.

Release data comes from `gh api` by default, or from `--releases-file` (a JSON
array of {repo, published_at, tag_name, body}) for offline runs and tests.

    python3 scripts/build_changelog.py            # rewrite changelog.mdx
    python3 scripts/build_changelog.py --check     # exit 1 if it would change
    python3 scripts/build_changelog.py --releases-file dump.json
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys

# repo -> (sidebar label/tag, how tags encode the package name, single-pkg name)
#   "scoped"   -> @scope/name@version   (npm)
#   "suffixed" -> name-vversion         (crates)
#   "at"       -> name@vversion         (vcpkg)
#   "single"   -> vversion, one package named by the third field (or None)
REPOS = {
    "npm": ("TypeScript", "scoped", None),
    "pypi": ("Python", "single", "resq-mcp"),
    "crates": ("Rust", "suffixed", None),
    "dotnet-sdk": (".NET", "single", None),
    "vcpkg": ("C++", "at", None),
}
ECOSYSTEM_ORDER = ["npm", "pypi", "crates", "dotnet-sdk", "vcpkg"]

# Scope renames: a package under the old scope is dropped from a month's table
# only when its counterpart under the new scope shipped that same month. This
# hides the abandoned-scope tail (e.g. @resq-sw/http's final release in July,
# superseded days later by @resq-systems/http) while preserving earlier months
# where only the old scope existed.
SCOPE_SUPERSESSION = {"@resq-sw/": "@resq-systems/"}

MONTHS = [
    "",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

START = "{/* CHANGELOG:AUTOGEN:START — edit scripts/build_changelog.py or automation/changelog-notes.md, not this region */}"
END = "{/* CHANGELOG:AUTOGEN:END */}"

CHANGELOG = "changelog.mdx"
NOTES = "automation/changelog-notes.md"


def parse_tag(
    repo: str, tag: str, default_pkg: str | None
) -> tuple[str | None, str] | None:
    """Return (package_or_None, version), or None if the tag is unparseable."""
    kind = REPOS[repo][1]
    if kind == "scoped":
        m = re.match(r"(@[\w-]+/[\w-]+)@v?(.+)", tag)
        return (m.group(1), m.group(2)) if m else None
    if kind == "suffixed":
        m = re.match(r"(.+)-v(\d.*)", tag)
        return (m.group(1), m.group(2)) if m else None
    if kind == "at":
        m = re.match(r"(.+)@v(\d.*)", tag)
        return (m.group(1), m.group(2)) if m else None
    m = re.match(r"v?(\d.*)", tag)  # single
    return (default_pkg, m.group(1)) if m else None


def version_key(v: str) -> tuple:
    return tuple(int(x) for x in re.findall(r"\d+", v)[:3]) or (0,)


def load_releases(releases_file: str | None) -> list[dict]:
    if releases_file:
        return json.loads(pathlib.Path(releases_file).read_text(encoding="utf-8"))
    out = []
    for repo in REPOS:
        raw = subprocess.run(
            [
                "gh",
                "api",
                "--paginate",
                "--slurp",
                f"repos/resq-software/{repo}/releases",
            ],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        for page in json.loads(raw):
            for r in page:
                if r.get("draft"):
                    continue
                out.append(
                    {
                        "repo": repo,
                        "published_at": r["published_at"],
                        "tag_name": r["tag_name"],
                        "body": r.get("body") or "",
                    }
                )
    return out


def latest_by_month(releases: list[dict]) -> dict[str, dict[str, dict[str, str]]]:
    """month 'YYYY-MM' -> repo -> package -> highest version released that month."""
    tree: dict[str, dict[str, dict[str, str]]] = {}
    for rel in releases:
        repo = rel["repo"]
        if repo not in REPOS:
            continue
        parsed = parse_tag(repo, rel["tag_name"], REPOS[repo][2])
        if not parsed:
            continue
        pkg, ver = parsed
        month = rel["published_at"][:7]
        by_pkg = tree.setdefault(month, {}).setdefault(repo, {})
        if pkg not in by_pkg or version_key(ver) > version_key(by_pkg[pkg]):
            by_pkg[pkg] = ver
    for month in tree.values():
        for packages in month.values():
            drop_superseded(packages)
    return tree


def drop_superseded(packages: dict[str, str]) -> None:
    """Remove old-scope packages whose new-scope counterpart shipped alongside."""
    for old_scope, new_scope in SCOPE_SUPERSESSION.items():
        new_bases = {
            p[len(new_scope) :] for p in packages if p and p.startswith(new_scope)
        }
        for pkg in list(packages):
            if pkg and pkg.startswith(old_scope) and pkg[len(old_scope) :] in new_bases:
                del packages[pkg]


def version_table(packages: dict[str, str]) -> list[str]:
    """Group packages by shared version so identical versions collapse to one row."""
    if not any(packages):  # single package, no name: state the version as prose
        return [f"Version {next(iter(packages.values()))}.", ""]

    by_version: dict[str, list[str]] = {}
    for pkg, ver in packages.items():
        by_version.setdefault(ver, []).append(pkg)

    rows = ["| Package | Version |", "|---------|---------|"]
    for ver in sorted(by_version, key=version_key, reverse=True):
        label = ", ".join(f"`{p}`" for p in sorted(by_version[ver]))
        rows.append(f"| {label} | {ver} |")
    rows.append("")
    return rows


def load_notes(root: pathlib.Path) -> dict[str, str]:
    """Parse automation/changelog-notes.md into {'YYYY-MM': markdown body}."""
    path = root / NOTES
    if not path.is_file():
        return {}
    notes: dict[str, str] = {}
    current = None
    buf: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^##\s+(\d{4}-\d{2})\s*$", line)
        if m:
            if current:
                notes[current] = "\n".join(buf).strip()
            current, buf = m.group(1), []
        elif current is not None:
            buf.append(line)
    if current:
        notes[current] = "\n".join(buf).strip()
    return {k: v for k, v in notes.items() if v}


def indent(text: str, pad: str = "  ") -> str:
    return "\n".join(pad + ln if ln else "" for ln in text.split("\n"))


def render(tree: dict, notes: dict[str, str]) -> str:
    blocks = []
    for month in sorted(tree, reverse=True):
        repos_present = [r for r in ECOSYSTEM_ORDER if r in tree[month]]
        tag_list = ", ".join(f'"{REPOS[r][0]}"' for r in repos_present)
        year, mon = month.split("-")
        label = f"{MONTHS[int(mon)]} {year}"

        body: list[str] = []
        note = notes.get(month)
        if note:
            body.append(indent(note))
            body.append("")
        for repo in repos_present:
            body.append(f"  ## {REPOS[repo][0]}")
            body.append("")
            body += [
                indent(ln) if ln else "" for ln in version_table(tree[month][repo])
            ]

        block = f'<Update label="{label}" tags={{[{tag_list}]}}>\n'
        block += "\n".join(body).rstrip() + "\n</Update>"
        blocks.append(block)
    return "\n\n".join(blocks)


def splice(existing: str, region: str) -> str:
    if START not in existing or END not in existing:
        raise SystemExit(f"{CHANGELOG} is missing the AUTOGEN markers")
    head = existing[: existing.index(START) + len(START)]
    tail = existing[existing.index(END) :]
    return f"{head}\n\n{region}\n\n{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", type=pathlib.Path)
    parser.add_argument("--releases-file")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if changelog.mdx is not up to date"
    )
    args = parser.parse_args()

    root = args.root.resolve()
    releases = load_releases(args.releases_file)
    tree = latest_by_month(releases)
    notes = load_notes(root)
    region = render(tree, notes)

    path = root / CHANGELOG
    existing = path.read_text(encoding="utf-8")
    updated = splice(existing, region)

    if args.check:
        if existing != updated:
            print(f"{CHANGELOG} is out of date — run scripts/build_changelog.py")
            return 1
        print(f"{CHANGELOG} is up to date ({len(tree)} month(s)).")
        return 0

    path.write_text(updated, encoding="utf-8")
    print(f"Wrote {CHANGELOG}: {len(tree)} month(s), {len(releases)} releases.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
