#!/usr/bin/env bash
# Sync canonical SDK auto-doc workflows from this repo's
# `automation/source-repo-templates/` into each SDK source repo's
# `.github/workflows/api-docs.yml`. Opens a sync PR per repo when a
# diff exists; reports up-to-date when not.
#
# Mapping is hard-coded (one entry per language) because there are
# only three SDKs and each has its own repo + default-branch quirk.
#
# Requirements:
#   - gh CLI authenticated with repo:write on each target repo
#   - git, mktemp
#
# Usage:
#   automation/sync-templates.sh                  # sync all 3
#   automation/sync-templates.sh dotnet           # sync just dotnet
#   automation/sync-templates.sh dotnet python    # sync subset
#
# Flags:
#   --dry-run    show diffs but don't open PRs
#   --auto-merge open PRs with --auto so they merge after CI
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_DIR="${REPO_ROOT}/automation/source-repo-templates"

# language|template_filename|target_repo|default_branch
TARGETS=(
  "typescript|api-docs.typescript.yml|resq-software/npm|master"
  "python|api-docs.python.yml|resq-software/pypi|main"
  "dotnet|api-docs.dotnet.yml|resq-software/dotnet-sdk|main"
  "rust|api-docs.rust.yml|resq-software/crates|master"
  "cpp|api-docs.cpp.yml|resq-software/vcpkg|main"
)

DRY_RUN=0
AUTO_MERGE=0
SELECTED_LANGS=()
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --auto-merge) AUTO_MERGE=1 ;;
    -*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *) SELECTED_LANGS+=("$arg") ;;
  esac
done

selected() {
  if [ ${#SELECTED_LANGS[@]} -eq 0 ]; then
    return 0
  fi
  for s in "${SELECTED_LANGS[@]}"; do
    [ "$s" = "$1" ] && return 0
  done
  return 1
}

sync_one() {
  local lang="$1" template_file="$2" target_repo="$3" default_branch="$4"

  if ! selected "$lang"; then
    return 0
  fi

  local template_path="${TEMPLATE_DIR}/${template_file}"
  if [ ! -f "$template_path" ]; then
    echo "[$lang] missing template: $template_path" >&2
    return 1
  fi

  echo "==> [$lang] checking $target_repo"
  local work
  work="$(mktemp -d)"
  trap 'rm -rf "$work"' RETURN

  local clone_dir="${work}/clone"
  if ! gh repo clone "$target_repo" "$clone_dir" -- \
        --depth=1 --branch="$default_branch" --quiet 2>/dev/null; then
    echo "[$lang] clone failed for $target_repo" >&2
    return 1
  fi

  local target_workflow="${clone_dir}/.github/workflows/api-docs.yml"
  local pre_existed=1
  if [ ! -f "$target_workflow" ]; then
    pre_existed=0
  fi
  mkdir -p "$(dirname "$target_workflow")"
  cp "$template_path" "$target_workflow"

  # `git diff` only reports modifications to tracked files; a brand
  # new workflow looks unchanged to it. Detect new-file case
  # explicitly by checking whether the path was tracked before copy.
  if [ "$pre_existed" -eq 1 ] && \
      git -C "$clone_dir" diff --quiet -- .github/workflows/api-docs.yml; then
    echo "[$lang] up-to-date"
    return 0
  fi

  if [ "$pre_existed" -eq 0 ]; then
    echo "[$lang] new workflow (none existed in target repo)"
  else
    echo "[$lang] diff:"
    git -C "$clone_dir" --no-pager diff --stat -- .github/workflows/api-docs.yml
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[$lang] dry-run, skipping PR"
    return 0
  fi

  local branch="sync/api-docs-template"
  local commit_msg
  commit_msg="$(cat <<EOF
ci(api-docs): sync workflow from resq-software/docs

Sync .github/workflows/api-docs.yml from the canonical template at
automation/source-repo-templates/${template_file} in
resq-software/docs.

Generated by automation/sync-templates.sh.
EOF
)"

  (
    cd "$clone_dir"
    git checkout -b "$branch"
    git add .github/workflows/api-docs.yml
    git -c user.email=engineer@resq.software \
        -c user.name="resq-sw" \
        commit -m "$commit_msg"
    git push -u origin "$branch" --force-with-lease
  )

  local pr_url
  pr_url="$(gh pr create \
    --repo "$target_repo" \
    --base "$default_branch" \
    --head "$branch" \
    --title "ci(api-docs): sync workflow from resq-software/docs" \
    --body "Sync from canonical template \`automation/source-repo-templates/${template_file}\`. Auto-generated by \`automation/sync-templates.sh\`." \
    2>&1 | tail -1)"
  echo "[$lang] $pr_url"

  if [ "$AUTO_MERGE" -eq 1 ]; then
    gh pr merge "$pr_url" --repo "$target_repo" --squash --auto --delete-branch || true
    echo "[$lang] auto-merge enabled"
  fi
}

failed=0
for entry in "${TARGETS[@]}"; do
  IFS='|' read -r lang template repo branch <<<"$entry"
  if ! sync_one "$lang" "$template" "$repo" "$branch"; then
    failed=$((failed + 1))
  fi
done

if [ "$failed" -gt 0 ]; then
  echo "==> $failed sync target(s) failed" >&2
  exit 1
fi

echo "==> done"
